In [ ]:
import numpy as np

In [ ]:
matrix = np.random.rand(10, 4)
matrix

array([[0.23365452, 0.10468768, 0.47797471, 0.03277128],
       [0.58285824, 0.30916075, 0.91410576, 0.7742852 ],
       [0.63524104, 0.60083833, 0.65731172, 0.40787302],
       [0.07010795, 0.040388  , 0.5594439 , 0.54482571],
       [0.75092133, 0.08212637, 0.6360212 , 0.66917158],
       [0.96328829, 0.45303725, 0.52127369, 0.39017341],
       [0.95546923, 0.91742954, 0.35547589, 0.11131584],
       [0.20564206, 0.35177939, 0.55136865, 0.69424437],
       [0.97123176, 0.89846284, 0.13024508, 0.10281114],
       [0.6660145 , 0.23613172, 0.99458109, 0.41517417]])

In [ ]:
matrix[:, 0]

array([0.23365452, 0.58285824, 0.63524104, 0.07010795, 0.75092133,
       0.96328829, 0.95546923, 0.20564206, 0.97123176, 0.6660145 ])

In [ ]:
exc = [0, 2, 5]
matrix[exc, :] = np.nan

In [ ]:
mask = np.ones(matrix.shape[0], dtype=bool)
mask[exc] = False

x1 = matrix[mask, 1]
x2 = matrix[mask, 2]

res = np.sum(matrix[mask, 1:])

matrix[mask, 0] = res

In [ ]:
matrix

array([[        nan,         nan,         nan,         nan],
       [10.28854818,  0.30916075,  0.91410576,  0.7742852 ],
       [        nan,         nan,         nan,         nan],
       [10.28854818,  0.040388  ,  0.5594439 ,  0.54482571],
       [10.28854818,  0.08212637,  0.6360212 ,  0.66917158],
       [        nan,         nan,         nan,         nan],
       [10.28854818,  0.91742954,  0.35547589,  0.11131584],
       [10.28854818,  0.35177939,  0.55136865,  0.69424437],
       [10.28854818,  0.89846284,  0.13024508,  0.10281114],
       [10.28854818,  0.23613172,  0.99458109,  0.41517417]])